TARGET = main

CPU = 65c02
INCLUDE = ../include
DEFINES = 
COMPILEFLAGS = 
LINKERFLAGS = -C W65C02.ld

BUILD_DIR = build
SOURCE_DIR = src
OBJECT_DIR = obj

OBJECT_FILES = $(patsubst $(SOURCE_DIR)/%.s, $(OBJECT_DIR)/%.o, $(wildcard $(SOURCE_DIR)/*.s))

.PHONY: all
all: Directories $(TARGET).bin

.PHONY: Directories
Directories: $(BUILD_DIR) $(OBJECT_DIR)

$(BUILD_DIR):
	mkdir -p $@

$(OBJECT_DIR):
	mkdir -p $@

$(TARGET).bin: $(OBJECT_FILES)
	ld65 $(LINKERFLAGS) $^ -o $(BUILD_DIR)/$@ -m $(BUILD_DIR)/$(TARGET).map -Ln $(BUILD_DIR)/symbols.txt

$(OBJECT_DIR)/%.o: $(SOURCE_DIR)/%.s
	ca65 --cpu $(CPU) $< -o $@ -I $(INCLUDE) $(COMPILEFLAGS) $(DEFINES) 

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR)
	rm -rf $(OBJECT_DIR)